project:
  type: book

book:
  title: "Estudio de Demanda Doctorado en Estudios de Género"
  subtitle: "Resultados - Encuesta"
  author: "María Fernanda Núñez"
  date: ""
 # date-format: "DD [de] MMMM, YYYY"
  language: es
 # cover-image: images/banner.png   # <- reemplaza este archivo por tu banner
#  cover-image-alt: "Banner de portada"
  navbar: 
    background: secondary
  page-footer:
 #   center: "![](images/banner.png)"
    background: "#1B2740"
    border: false
#    right: ""
  chapters:
    - index.qmd
    - 01-seccion1.qmd
    - 02-seccion2.qmd
    - 03-seccion3.qmd
  page-navigation: true
  search: true
  
      # color del texto/íconos

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    code-tools: false
    fig-align: center
    fig-dpi: 300
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    fig-align: center
    fig-dpi: 300

execute:
  echo: true
  warning: false
  message: false
